# Generated by Django 5.2.6 on 2025-09-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptechApp', '0005_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
