# Generated by Django 5.2.6 on 2025-09-23 08:52

from django.db import migrations
import uuid

def generate_codes(apps, schema_editor):
    Product = apps.get_model("shoptechApp", "Product")
    for product in Product.objects.all():
        if not product.product_code:
            product.product_code = str(uuid.uuid4())
            product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('shoptechApp', '0006_contactus'),
    ]

    operations = [
        migrations.RunPython(generate_codes),
    ]
