# Generated by Django 5.2.6 on 2025-09-23 08:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptechApp', '0007_auto_20250923_0852'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.CharField(choices=[('rings', 'Rings'), ('necklaces', 'Necklaces'), ('bangles', 'Bangles'), ('earrings', 'Earrings')], default='rings', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
