# Generated by Django 5.2.6 on 2025-09-23 09:00

import shoptechApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptechApp', '0009_alter_product_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_code',
            field=models.CharField(default=shoptechApp.models.generate_product_code, editable=False, max_length=50, unique=True),
        ),
    ]
