name: Backend CI/CD

on:
  push:
    branches: [ "main", "develop", "feature/mpesa" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python shoptech/manage.py test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/manhattan-backend:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/manhattan-backend:${{ github.ref_name }}
            docker stop backend || true
            docker rm backend || true
            docker run -d --name backend -p 8000:8000 ${{ secrets.DOCKER_USERNAME }}/manhattan-backend:${{ github.ref_name }}
