name: Backend CI/CD

on:
  push:
    branches: [ "main", "develop", "feature/mpesa" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/manhattan-backend:${{ github.ref_name }}
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy to AWS
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/manhattan-backend:${{ github.ref_name }}
            docker stop backend || true
            docker rm backend || true

            docker run -d --name backend -p 8000:8000 \
              -e "SECRET_KEY=${{ secrets.SECRET_KEY }}" \
              -e "DEBUG=False" \
              -e "ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }}" \
              -e "DB_NAME=${{ secrets.DB_NAME }}" \
              -e "DB_USER=${{ secrets.DB_USER }}" \
              -e "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" \
              -e "DB_HOST=${{ secrets.DB_HOST }}" \
              -e "DB_PORT=${{ secrets.DB_PORT }}" \
              -e "CONSUMER_KEY=${{ secrets.CONSUMER_KEY }}" \
              -e "CONSUMER_SECRET=${{ secrets.CONSUMER_SECRET }}" \
              -e "MPESA_PASSKEY=${{ secrets.MPESA_PASSKEY }}" \
              -e "BUSINESS_SHORTCODE=${{ secrets.BUSINESS_SHORTCODE }}" \
              -e "MPESA_CALLBACK_URL=${{ secrets.MPESA_CALLBACK_URL }}" \
              -e "MPESA_BASE_URL=${{ secrets.MPESA_BASE_URL }}" \
              ${{ secrets.DOCKER_USERNAME }}/manhattan-backend:${{ github.ref_name }}


            # Run migrations inside the container
            docker exec backend python manage.py migrate --noinput

            # Collect static files
            docker exec backend python manage.py collectstatic --noinput